<a href="https://colab.research.google.com/github/MAB1144-Python/CD_databits/blob/main/03_Python_Librer%C3%ADas_para_Ciencia_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



<div style="text-align: center; line-height: 0; padding-top: 9px;">
  <img src="https://storage.googleapis.com/datasets-academy/public-img/notebooks/headers/databits-header-notebook.png" alt="Databricks Learning" style="width: 100%;">
</div>



# <center>  Librerías para Ciencia de Datos </center>

## Descripción
En esta lección se trabajará con las principales librerías enfocadas en Ciencia de Datos

## Contenido

* Arreglos n-dimensionales y operaciones con NumPy
* Series y Dataframes con Pandas
* Manipulación de DataFrames con Pandas


## Audiencia

* Audiencia primaria: Desarrolladores, Ingenieros y Científicos de datos y Analistas de BI

## Requisitos previos

* Conocimientos básicos de programación
* Navegador web: Chrome

<img alt="Caution" title="Caution" style="vertical-align: text-bottom; position: relative; height:1.3em; top:0.0em" src="https://storage.googleapis.com/datasets-academy/public-img/notebooks/icons/danger.png"/> **Disclaimer:** Este material ha sido preparado por el equipo de **handytec Academy®**. Se prohibe la publicación o reproducción de este material sin previa autorización de **handytec Academy®** - 2022 Todos los derechos reservados.

### Programación orientada a objetos en Python

#### Clases / Objetos
En la verdadera programación orientada a objetos (OOP), el desarrollador escribe código en torno a cosas llamadas objetos. Un objeto (o una clase) agrupa datos y funciones que operan sobre esos datos. Es posible que conozca esta terminología de *C++* y otros lenguajes.

#### Módulos
Los módulos en Python contienen grandes cantidades de código que se encuentran relacionados. En la mayoría de los casos, poseen varias clases y funciones que abordan una necesidad particular. 

#### Librerías / Bibliotecas
Las librerías pueden contener múltiples módulos que van juntos. Las librerías generalmente tiene una estructura de directorio específica.

### Importar Módulos
Todo notebook debería empezar con una sección de código que importe los **módulos** que se emplearán.

A continuación importaremos el módulo **numpy** y **pandas**. Estas son librerías comúnmente empleadas en el área de la Ciencia de Datos. 

De manera general, utilizaremos la estructura `import MODULE_NAME as MODULE_NICKNAME` para importar cualquier módulo que la programación requiera.

In [ ]:
#!pip install numpy
import numpy as np
import pandas as pd
      

### Buena práctica: verificar versión actual de librerías

In [ ]:
print('** Versiones Actuales | Requeridas **')
print('NumPy: Version Actual:', np.__version__)
print('Pandas: Version Actual:', pd.__version__)

** Versiones Actuales | Requeridas **
NumPy: Version Actual: 1.21.6
Pandas: Version Actual: 1.3.5


## 1. Arreglos n-dimensionales y operaciones con NumPy
NumPy es una librería optimizada para programación numérica a través de procesamiento de datos en arreglos multidimensionales. <br>

Optimiza operaciones tradicionales que se realizan a través de bucles o tipos de datos primitivos, gracias a su mecanismo de procesar las operaciones a través de lotes en códigos optimizados en C y Fortran.

[NumPy](https://numpy.org/devdocs/index.html) define estructuras de datos de tipo *ndarrays* : arreglos n-dimensionales.
### 1.1 Arreglos en 1D:

In [ ]:
# Emplear listas para la creación de ndarrays, por medio de la función np.array
lt = [1, 2, 3, 5]
print(lt)
A = np.asarray(lt)
print(A)
print(type(A))

[1, 2, 3, 5]
[1 2 3 5]
<class 'numpy.ndarray'>


In [ ]:
B = [1,4.5, 3.6]
C = np.array(B)
C.dtype

dtype('float64')

In [ ]:
# Métodos para analizar propiedades en un ndarray
print ('Forma (filas, columnas): ', A.shape)
print ('Número de dimensiones', A.ndim)
print ('Tipo de dato: ', A.dtype)

Forma (filas, columnas):  (4,)
Número de dimensiones 1
Tipo de dato:  int64


Selección de elementos por indexado o slicing en un vector

In [ ]:
print(A)
print(A[-2])
print(A[2:])

[1 2 3 5]
3
[3 5]


Operaciones aritméticas `(+ , - , *, /, //, **, %)`  en los ndarrays son de elemento a elemento con arreglos del mismo tamaño (caso contrario se aplica **broadcasting**)

In [ ]:
A1 = [1,2,3]
B1 = [4,5,6]
A1 + B1

[1, 2, 3, 4, 5, 6]

In [ ]:
A2 = np.array([1,2,3])
B2 = np.array([4,5,6])
A2 + B2

array([5, 7, 9])

In [ ]:
A

array([1, 2, 3, 5])

In [ ]:
# Operaciones entre ndarrays
B = np.array([2,1,0,3])
A ** B

array([  1,   2,   1, 125])

### 1.2 Arreglos en 2D:

In [ ]:
# Emplear una lista de listas para la creación de un ndarray de dos dimensiones
T = np.array([[3, 4, 2],
              [6, 1, 9],
              [5, 7, 8.0]])
print(T)

[[3. 4. 2.]
 [6. 1. 9.]
 [5. 7. 8.]]


In [ ]:
# Métodos para analizar propiedades en un ndarray
print ('Forma (filas,cols): ', T.shape)
print ('Número de dimesiones:', T.ndim)
print ('Tipo dato de elementos: ', T.dtype)

Forma (filas,cols):  (3, 3)
Número de dimesiones: 2
Tipo dato de elementos:  float64


Selección de elementos por indexado y slicing en una matriz

In [ ]:
# Selección de un elemento en una matriz: ndarray[filas][columnas]
print(T)
print(T[1])

[[3. 4. 2.]
 [6. 1. 9.]
 [5. 7. 8.]]
[6. 1. 9.]


In [ ]:
# Selección de varios elementos en una matriz: ndarray[filas, columnas]
print(T[1:2, 1:3])

[[1. 9.]]


In [ ]:
list(T)

[array([3., 4., 2.]), array([6., 1., 9.]), array([5., 7., 8.])]

### 1.3 Funciones básicas en NumPy

Podemos especificar el tipo de dato requerido a través del parámetro **dtype**:

In [ ]:
#Creación de ndarrays con valores de cero, empleando la función np.zeros
cero_array = np.zeros((4,3), dtype = float)
cero_array[2][1] = 5 
print(cero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 5. 0.]
 [0. 0. 0.]]


In [ ]:
#Creación de ndarrays con valores de cero, empleando la función np.ones
uno_array = np.ones((3,4), dtype = float)
uno_array[2][1] = 5.10 
print(uno_array)

[[1.  1.  1.  1. ]
 [1.  1.  1.  1. ]
 [1.  5.1 1.  1. ]]


In [ ]:
#Creación de un ndarray con un rango de valores, empleando la función np.arange(inicio, fin-1, step)
rango = np.arange(0, 1, 0.1)
print(rango)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### 1.4 Métodos útiles para aplanar y cambiar la forma de un ndarray

In [ ]:
# El método reshape permite cambiar la forma de un ndarray
rango_reshape = rango.reshape(5, 2)
print(rango_reshape)

[[0.  0.1]
 [0.2 0.3]
 [0.4 0.5]
 [0.6 0.7]
 [0.8 0.9]]


In [ ]:
# El método ravel permite aplanar un ndarray
rango_flat = rango_reshape.ravel()
print(rango_flat)
print(T.ravel())

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[3. 4. 2. 6. 1. 9. 5. 7. 8.]


### 1.5 Funciones estadísticas en NumPy

Al ser arreglos que pueden tener 1 o más dimensiones, las funciones pueden involucrar todos los elementos, o los elementos por cada una de las dimensiones.<br>
A continuación algunas de las funciones más utilizados en NumPy (siendo X un ``ndarray``):
    - Suma: np.sum(X)
    - Raíz cuadrada: np.sqrt(X)
    - Promedio: np.mean(X)
    - Varianza: np.var(X)
    - Ordenamiento: np.sort(X)
    - Maximo, Minimo: np.max(X), np.min(X)
    - Indice de posición del valor Maximo: np.argmax(X)
    - Indice de posición del valor Minimo: np.argmin(X)

In [ ]:
#La función np.random.randint genera números aleatorios enteros: np.random.randint(inicio, fin-1, (filas, columnas))
np.random.seed(0)
A = np.random.randint(1,5,(3,5)) 
print(A)

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]]


In [ ]:
np.random.randint(1,5)

1

In [ ]:
#SUMA TOTAL
print(np.sum(A))

43


In [ ]:
#SUMA POR COLUMNAS
print(np.sum(A, axis = 0))

[ 7 11  7  7 11]


In [ ]:
#SUMA POR FILAS
print(np.sum(A, axis = 1))

[12 18 13]


#### 1.6 Broadcasting

Permite realizar operaciones aritméticas entre ndarrays de distintos tamaños

![](https://www.astroml.org/_images/fig_broadcast_visual_1.png)

In [ ]:
# Operación de un ndarray con un escalar
np.arange(3) + 5

array([5, 6, 7])

## 2. Series y Dataframes con Pandas

Nos gustaría una estructura de datos que pueda almacenar fácilmente variables de diferentes tipos, que almacene nombres de columnas, y en la que podamos hacer referencia por nombre de columna así como por posición indexada. Y sería bueno si esta estructura de datos viniera con funciones integradas que podamos usar para manipularla.

`Pandas` es una librería que hace todo esto! La librería está construida sobre `numpy`.

Existen dos objetos `pandas` básicos, *series* y *dataframes*, que se pueden considerar como versiones mejoradas de arreglos 1D y 2D `numpy`, respectivamente. 

Para referencia `pandas` [cheatsheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) y `pandas` [documentación](https://pandas.pydata.org/pandas-docs/stable/).

**Importancia de Pandas**
*    Lectura y escritura de datos 
*    Modificación de índices y etiquetas de las columnas
*    Trabajo con fechas
*    Ordenamiento, agrupación y tratamiento de valores faltantes (curación de datos)
    
Para importar este módulo utilizamos el comando: ```import pandas as pd```

### 2.1 Pandas - Series

Una Serie es una colección de observaciones de una variable individual. <br>

Se puede pensar en una Serie como los datos en un arreglo de 1D.

En la serie ``items``, cada uno de los índices del 0 al 4 son los identificadores de 5 productos diferentes y los valores float representan el precio unitario correspondiente a cada uno.

In [ ]:
# Usamos el constructor pd.Series
items = pd.Series(data = np.array([2, 3, 'ocho', 6, 7]), name = 'precios', index = ['veg1','cer1','frut1','frut2','frut3'])
print(items)

veg1        2
cer1        3
frut1    ocho
frut2       6
frut3       7
Name: precios, dtype: object


**Importante**: las Series están implementadas sobre arreglos NumPy. Esto les permite soportar operaciones válidas con estos arreglos. En el ejemplo tenemos el caso de la multiplicación de un arreglo de 1D por un escalar.

Método útiles de las Series de Pandas

In [ ]:
print('Obtener los índices:', items.index)
print('Obtener los valores:', items.values)
print('Obtener tipo de dato:', items.dtypes)

Obtener los índices: Index(['veg1', 'cer1', 'frut1', 'frut2', 'frut3'], dtype='object')
Obtener los valores: ['2' '3' 'ocho' '6' '7']
Obtener tipo de dato: object


### 2.2 Pandas - DataFrames: creación, propiedades y funciones

Un DataFrame de Pandas es un objeto que permite guardar datos en varias columnas que estan mutuamente relacionadas. 

Podemos pensar un DataFrame como una hoja de datos de Excel altamente optimizada. Los DataFrames estan compuestos por filas y columnas.

Pandas posee múltiples funciones para cargar varios tipos de archivos: pd.read_csv, pd.read_excel, pd.read_json, pd.read_parquet, etc.


### Lectura de datos en un DataFrame

A continuación, iniciaremos leyendo los datos del archivo en formato csv en un DataFrame. <br>

Este archivo contiene una muestra de datos de 'Penn World Table' con diferentes indicadores socioeconómicos de los países en diferentes años. 

<a href='https://storage.googleapis.com/datasets-academy/Track%20Data%20Science/01_Intro_Python/PWT91.csv'>
  Link para descargar el dataset PWT</a>

**Diccionario de datos:**

**countrycode:** Código estándar ISO 3166-1 alfa-3, proporciona códigos para los nombres de países por medio de tres letras<br>
**country:** Nombre del país <br>
**year:** Año <br>
**rgdpo:** Producto Interno Bruto Real calculado mediante la PPA (pariedad de poder adquisitivo) con año base 2011 (en millones dólares) <br>
**pop:** Población (millones de personas) <br>
**emp:** Personas de 15 años y más que durante la semana trabajaron incluso solo durante una hora, o no estaban en el trabajo pero tenían un trabajo o negocio del que estaban temporalmente ausentes (millones de personas) <br>
**avh:** Promedio de horas anuales trabajadas por personas que cumplan la condición de la variable emp <br>
**hc:** Índice de capital humano por persona, que se relaciona con los años promedio de escolaridad y el retorno a la educación

In [ ]:
# Nomeclatura estándar para el nombre de un Dataframe se abrevia con df
df = pd.read_csv(filepath_or_buffer = 'https://storage.googleapis.com/datasets-academy/Track%20Data%20Science/01_Intro_Python/PWT91.csv', 
                 sep = ',', 
                 decimal = '.',
                 )

# El método head permite observar las primeras 5 filas del dataframe
df.head(200)

countrycode   country  year       rgdpo       pop  emp  avh  hc
0           ABW     Aruba  1950         NaN       NaN  NaN  NaN NaN
1           ABW     Aruba  1951         NaN       NaN  NaN  NaN NaN
2           ABW     Aruba  1952         NaN       NaN  NaN  NaN NaN
3           ABW     Aruba  1953         NaN       NaN  NaN  NaN NaN
4           ABW     Aruba  1954         NaN       NaN  NaN  NaN NaN
..          ...       ...   ...         ...       ...  ...  ...  ..
195         AIA  Anguilla  2009  299.144043  0.013565  NaN  NaN NaN
196         AIA  Anguilla  2010  290.499145  0.013769  NaN  NaN NaN
197         AIA  Anguilla  2011  294.841003  0.013951  NaN  NaN NaN
198         AIA  Anguilla  2012  277.228668  0.014129  NaN  NaN NaN
199         AIA  Anguilla  2013  250.532318  0.014299  NaN  NaN NaN

[200 rows x 8 columns]

**Fuente**: Feenstra, Robert C., Robert Inklaar and Marcel P. Timmer (2015), "The Next Generation of the Penn World Table" American Economic Review, 105(10), 3150-3182, available for download at www.ggdc.net/pwt

Lo que tenemos ahora es una hoja de cálculo con filas indexadas y columnas nombradas, llamada `df`. **Importante**: Las columnas son *series de pandas*.

In [ ]:
# Comprobamos las dimensiones del Dataframe (filas, columnas)
df.shape

(12376, 8)

In [ ]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


La función `pd.read_csv` infiere el tipo de datos por defecto

In [ ]:
# Comprobamos el tipo de las variables en el dataframe
print(df.dtypes)

countrycode     object
country         object
year             int64
rgdpo          float64
pop            float64
emp            float64
avh            float64
hc             float64
dtype: object


In [ ]:
df.keys()

Index(['countrycode', 'country', 'year', 'rgdpo', 'pop', 'emp', 'avh', 'hc'], dtype='object')

Podemos cambiar el tipo de las columnas:
- Convertir la columna year para que sea tipo datetime, para una mayor información sobre los tipos de [formatos fecha](https://strftime.org/)
- Convertir la columna pop (población)

In [ ]:
df['year']# para una sola

0        1950
1        1951
2        1952
3        1953
4        1954
         ... 
12371    2013
12372    2014
12373    2015
12374    2016
12375    2017
Name: year, Length: 12376, dtype: int64

In [ ]:
list_cl = ['year','rgdpo','countrycode','pop','year','hc']
df1 = df[list_cl]
df1

year        rgdpo countrycode        pop  year        hc
0      1950          NaN         ABW        NaN  1950       NaN
1      1951          NaN         ABW        NaN  1951       NaN
2      1952          NaN         ABW        NaN  1952       NaN
3      1953          NaN         ABW        NaN  1953       NaN
4      1954          NaN         ABW        NaN  1954       NaN
...     ...          ...         ...        ...   ...       ...
12371  2013  28329.81055         ZWE  15.054506  2013  2.504635
12372  2014  29355.75977         ZWE  15.411675  2014  2.550258
12373  2015  29150.75000         ZWE  15.777451  2015  2.584653
12374  2016  29420.44922         ZWE  16.150362  2016  2.616257
12375  2017  30940.81641         ZWE  16.529903  2017  2.648248

[12376 rows x 6 columns]

In [ ]:
df2 = df[['year','country','hc']]
df2.dtypes

year         int64
country     object
hc         float64
dtype: object

In [ ]:
#2013-12-3 12:3:251 %Y-%m-%d %H:%M:%S
#05 / agosto de 2022
df['year'] = pd.to_datetime(df['year'], format = '%Y')
df['pop']  = df['pop'].fillna(0).astype(int)
df

countrycode   country       year        rgdpo  pop       emp  avh  \
0             ABW     Aruba 1950-01-01          NaN    0       NaN  NaN   
1             ABW     Aruba 1951-01-01          NaN    0       NaN  NaN   
2             ABW     Aruba 1952-01-01          NaN    0       NaN  NaN   
3             ABW     Aruba 1953-01-01          NaN    0       NaN  NaN   
4             ABW     Aruba 1954-01-01          NaN    0       NaN  NaN   
...           ...       ...        ...          ...  ...       ...  ...   
12371         ZWE  Zimbabwe 2013-01-01  28329.81055   15  7.914061  NaN   
12372         ZWE  Zimbabwe 2014-01-01  29355.75977   15  8.222112  NaN   
12373         ZWE  Zimbabwe 2015-01-01  29150.75000   15  8.530669  NaN   
12374         ZWE  Zimbabwe 2016-01-01  29420.44922   16  8.839398  NaN   
12375         ZWE  Zimbabwe 2017-01-01  30940.81641   16  9.181251  NaN   

             hc  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN  
...         ...  
12371  2.504635  
12372  2.550258  
12373  2.584653  
12374  2.616257  
12375  2.648248  

[12376 rows x 8 columns]

In [ ]:
df_1  = df['emp'].fillna('0')
df_1

0               0
1               0
2               0
3               0
4               0
           ...   
12371    7.914061
12372    8.222112
12373    8.530669
12374    8.839398
12375    9.181251
Name: emp, Length: 12376, dtype: object

In [ ]:
df['pop']  = df['pop'].fillna(0).astype(int)
df

countrycode   country       year        rgdpo  pop       emp  avh  \
0             ABW     Aruba 1950-01-01          NaN    0       NaN  NaN   
1             ABW     Aruba 1951-01-01          NaN    0       NaN  NaN   
2             ABW     Aruba 1952-01-01          NaN    0       NaN  NaN   
3             ABW     Aruba 1953-01-01          NaN    0       NaN  NaN   
4             ABW     Aruba 1954-01-01          NaN    0       NaN  NaN   
...           ...       ...        ...          ...  ...       ...  ...   
12371         ZWE  Zimbabwe 2013-01-01  28329.81055   15  7.914061  NaN   
12372         ZWE  Zimbabwe 2014-01-01  29355.75977   15  8.222112  NaN   
12373         ZWE  Zimbabwe 2015-01-01  29150.75000   15  8.530669  NaN   
12374         ZWE  Zimbabwe 2016-01-01  29420.44922   16  8.839398  NaN   
12375         ZWE  Zimbabwe 2017-01-01  30940.81641   16  9.181251  NaN   

             hc  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN  
...         ...  
12371  2.504635  
12372  2.550258  
12373  2.584653  
12374  2.616257  
12375  2.648248  

[12376 rows x 8 columns]

## 3. Manipulación de DataFrames con Pandas

### Selección de filas y columnas de un DataFrame utilizando ```iloc```
Cuando queremos seleccionar filas y columnas de acuerdo a la posición del índice, utilizamos el atributo:<br>
```iloc[indiceInicioFilas:indiceFinFilas-1 , indiceInicioCols:indiceFinCols-1]```

In [ ]:
#Seleccion de las filas por posición y las tres primeras columnas
df.iloc[2300:2303, :2]

countrycode country
2300         CHN   China
2301         CHN   China
2302         CHN   China

### Selección de filas y columnas de un DataFrame utilizando ```loc```
Cuando queremos seleccionar filas y columnas de acuerdo a una mezcla del nombre de los índices y nombres de las columnas (etiquetas), utilizamos el atributo: ```loc[]```

In [ ]:
 df.keys()

Index(['countrycode', 'country', 'year', 'rgdpo', 'pop', 'emp', 'avh', 'hc'], dtype='object')

In [ ]:
df_seleccion = df.loc[10:15, ['countrycode', 'year', 'pop', 'rgdpo']]
df_seleccion.head()
#NaN nan Nan NaT None null inf 

countrycode       year  pop  rgdpo
10         ABW 1960-01-01    0    NaN
11         ABW 1961-01-01    0    NaN
12         ABW 1962-01-01    0    NaN
13         ABW 1963-01-01    0    NaN
14         ABW 1964-01-01    0    NaN

In [ ]:
df.keys()

Index(['countrycode', 'country', 'year', 'rgdpo', 'pop', 'emp', 'avh', 'hc'], dtype='object')

### Renombrar columnas en un DataFrame

In [ ]:
df_seleccion.rename(columns = {'countrycode': 'codigo_pais', 'pop': 'pob_millones', 'rgdpo': 'pib_real_millones'}, inplace = True)
df_seleccion.keys()

Index(['codigo_pais', 'year', 'pob_millones', 'pib_real_millones'], dtype='object')

>**Ejercicio 1:** Utilizando el método `rename` y la opción `inplace=False`, cambie el nombre de la columna `codigo_pais` por `codigo_iso` en el dataframe `df_seleccion`. Utilizando el método `columns` verifique si el cambio de nombre se grabó de forma permanente en `df_seleccion`.

In [ ]:
# archivo
df_seleccion = df.loc[:, ['countrycode', 'year', 'pop', 'rgdpo']]
#### Ejercicio 1
print(df_seleccion.head())
df_seleccion.rename(columns = {'countrycode': 'codigo_iso'}, inplace = True)
df_seleccion 

  countrycode       year  pop  rgdpo
0         ABW 1950-01-01    0    NaN
1         ABW 1951-01-01    0    NaN
2         ABW 1952-01-01    0    NaN
3         ABW 1953-01-01    0    NaN
4         ABW 1954-01-01    0    NaN


codigo_iso       year  pop        rgdpo
0            ABW 1950-01-01    0          NaN
1            ABW 1951-01-01    0          NaN
2            ABW 1952-01-01    0          NaN
3            ABW 1953-01-01    0          NaN
4            ABW 1954-01-01    0          NaN
...          ...        ...  ...          ...
12371        ZWE 2013-01-01   15  28329.81055
12372        ZWE 2014-01-01   15  29355.75977
12373        ZWE 2015-01-01   15  29150.75000
12374        ZWE 2016-01-01   16  29420.44922
12375        ZWE 2017-01-01   16  30940.81641

[12376 rows x 4 columns]

### Solución

In [ ]:
print('Resolución;')
df_seleccion.rename(columns = {'codigo_pais': 'codigo_iso'}, inplace = False)
df_seleccion.columns

Resolución;


Index(['codigo_iso', 'year', 'pop', 'rgdpo'], dtype='object')

### Filtrado del DataFrame

In [ ]:
#to_time(format = '%Y')
df_seleccion['year']

0       1950-01-01
1       1951-01-01
2       1952-01-01
3       1953-01-01
4       1954-01-01
           ...    
12371   2013-01-01
12372   2014-01-01
12373   2015-01-01
12374   2016-01-01
12375   2017-01-01
Name: year, Length: 12376, dtype: datetime64[ns]

In [ ]:
df_seleccion.dtypes

codigo_iso            object
year          datetime64[ns]
pop                    int64
rgdpo                float64
dtype: object

In [ ]:
# Condición booleana de una Serie de Pandas (indexado condicional)
df_seleccion['year'] > np.array('2015-01-01', dtype=np.datetime64)

0        False
1        False
2        False
3        False
4        False
         ...  
12371    False
12372    False
12373    False
12374     True
12375     True
Name: year, Length: 12376, dtype: bool

In [ ]:
# Filtramos por filas a partir de una condición en la columna year (fechas mayores a 2015)
df_filtrado = df_seleccion.loc[df_seleccion['year'] > np.array('2015-01-01', dtype=np.datetime64)]
df_filtrado

codigo_iso       year  pop          rgdpo
66           ABW 2016-01-01    0    3101.279785
67           ABW 2017-01-01    0    3144.354980
134          AGO 2016-01-01   28  151165.046900
135          AGO 2017-01-01   29  148737.671900
202          AIA 2016-01-01    0     227.307556
...          ...        ...  ...            ...
12239        ZAF 2017-01-01   56  665931.562500
12306        ZMB 2016-01-01   16   58932.542970
12307        ZMB 2017-01-01   17   63231.378910
12374        ZWE 2016-01-01   16   29420.449220
12375        ZWE 2017-01-01   16   30940.816410

[364 rows x 4 columns]

>**Ejercicio 2:** Generar un nuevo dataframe llamado `df_mayor_pob` realizando un filtrado de las filas del dataframe `df_filtrado`, si la población es mayor a 200 millones de habitantes.

In [ ]:
print(df_filtrado.keys())
# Su código aquí
df_mayor_pob = df_filtrado.loc[df_filtrado['pop'] > 200]
df_mayor_pob = df_filtrado[df_filtrado['pop'] > 200]
df_mayor_pob


Index(['codigo_iso', 'year', 'pop', 'rgdpo'], dtype='object')


codigo_iso       year   pop        rgdpo
1698         BRA 2016-01-01   207   2863052.75
1699         BRA 2017-01-01   209   2890897.50
2310         CHN 2016-01-01  1403  17360582.00
2311         CHN 2017-01-01  1409  18383838.00
5234         IDN 2016-01-01   261   2643358.50
5235         IDN 2017-01-01   263   2796742.50
5302         IND 2016-01-01  1324   7995329.50
5303         IND 2017-01-01  1339   8599774.00
11762        USA 2016-01-01   322  17392620.00
11763        USA 2017-01-01   324  17778680.00

In [ ]:
df_seleccion['year'] = pd.to_datetime(df_seleccion['year'], format = '%Y')
df_seleccion['pop']  = df['pop'].fillna(0).astype(int)
#df.dtypes
df_seleccion
 
df_filtrado = df_seleccion.loc[df_seleccion['year'] > np.array('2015-01-01', dtype=np.datetime64)]
df_filtrado
 
df_mayor_pob = df_filtrado.loc[df_filtrado['pop'] > 200]
df_mayor_pob

codigo_iso       year   pop        rgdpo
1698         BRA 2016-01-01   207   2863052.75
1699         BRA 2017-01-01   209   2890897.50
2310         CHN 2016-01-01  1403  17360582.00
2311         CHN 2017-01-01  1409  18383838.00
5234         IDN 2016-01-01   261   2643358.50
5235         IDN 2017-01-01   263   2796742.50
5302         IND 2016-01-01  1324   7995329.50
5303         IND 2017-01-01  1339   8599774.00
11762        USA 2016-01-01   322  17392620.00
11763        USA 2017-01-01   324  17778680.00

### Solución

In [ ]:
df_mayor_pob = df_filtrado.loc[df_filtrado['pob_millones'] > 200]
df_mayor_pob

KeyError: ignored

### Creación de nuevas columnas

In [ ]:
print(df_mayor_pob.keys())
df_percapita = df_mayor_pob.copy()
df_percapita.loc[:, 'pib_percapita'] = df_percapita['rgdpo'] / df_percapita['pop']
df_percapita['pib_percapita_2'] = (df_percapita['rgdpo'] / df_percapita['pop'])**2
df_percapita

Index(['codigo_iso', 'year', 'pop', 'rgdpo'], dtype='object')


codigo_iso       year   pop        rgdpo  pib_percapita  pib_percapita_2
1698         BRA 2016-01-01   207   2863052.75   13831.172705     1.913013e+08
1699         BRA 2017-01-01   209   2890897.50   13832.045455     1.913255e+08
2310         CHN 2016-01-01  1403  17360582.00   12373.900214     1.531134e+08
2311         CHN 2017-01-01  1409  18383838.00   13047.436480     1.702356e+08
5234         IDN 2016-01-01   261   2643358.50   10127.810345     1.025725e+08
5235         IDN 2017-01-01   263   2796742.50   10634.001901     1.130820e+08
5302         IND 2016-01-01  1324   7995329.50    6038.768505     3.646673e+07
5303         IND 2017-01-01  1339   8599774.00    6422.534727     4.124895e+07
11762        USA 2016-01-01   322  17392620.00   54014.347826     2.917550e+09
11763        USA 2017-01-01   324  17778680.00   54872.469136     3.010988e+09

### Ordenamiento en el DataFrame

In [ ]:
df_percapita.sort_values(by='pop', ascending = True)

codigo_iso       year   pop        rgdpo  pib_percapita  pib_percapita_2
1698         BRA 2016-01-01   207   2863052.75   13831.172705     1.913013e+08
1699         BRA 2017-01-01   209   2890897.50   13832.045455     1.913255e+08
5234         IDN 2016-01-01   261   2643358.50   10127.810345     1.025725e+08
5235         IDN 2017-01-01   263   2796742.50   10634.001901     1.130820e+08
11762        USA 2016-01-01   322  17392620.00   54014.347826     2.917550e+09
11763        USA 2017-01-01   324  17778680.00   54872.469136     3.010988e+09
5302         IND 2016-01-01  1324   7995329.50    6038.768505     3.646673e+07
5303         IND 2017-01-01  1339   8599774.00    6422.534727     4.124895e+07
2310         CHN 2016-01-01  1403  17360582.00   12373.900214     1.531134e+08
2311         CHN 2017-01-01  1409  18383838.00   13047.436480     1.702356e+08

In [ ]:
df_percapita.sort_values(by='codigo_iso', ascending = True)

### Agregación en DataFrames

#### Uso la función groupby

Busca agrupar grandes cantidades de datos y aplicar operaciones de cálculo en estos grupos

In [ ]:
df_percapita

codigo_iso       year   pop        rgdpo  pib_percapita  pib_percapita_2
1698         BRA 2016-01-01   207   2863052.75   13831.172705     1.913013e+08
1699         BRA 2017-01-01   209   2890897.50   13832.045455     1.913255e+08
2310         CHN 2016-01-01  1403  17360582.00   12373.900214     1.531134e+08
2311         CHN 2017-01-01  1409  18383838.00   13047.436480     1.702356e+08
5234         IDN 2016-01-01   261   2643358.50   10127.810345     1.025725e+08
5235         IDN 2017-01-01   263   2796742.50   10634.001901     1.130820e+08
5302         IND 2016-01-01  1324   7995329.50    6038.768505     3.646673e+07
5303         IND 2017-01-01  1339   8599774.00    6422.534727     4.124895e+07
11762        USA 2016-01-01   322  17392620.00   54014.347826     2.917550e+09
11763        USA 2017-01-01   324  17778680.00   54872.469136     3.010988e+09

In [ ]:
# Agregamos los datos mediante empleando el promedio
print(df.keys())
df_filt = df.groupby(['countrycode','year']).count().reset_index()
df_filt

Index(['countrycode', 'country', 'year', 'rgdpo', 'pop', 'emp', 'avh', 'hc'], dtype='object')


countrycode       year  country  rgdpo  pop  emp  avh  hc
0             ABW 1950-01-01        1      0    1    0    0   0
1             ABW 1951-01-01        1      0    1    0    0   0
2             ABW 1952-01-01        1      0    1    0    0   0
3             ABW 1953-01-01        1      0    1    0    0   0
4             ABW 1954-01-01        1      0    1    0    0   0
...           ...        ...      ...    ...  ...  ...  ...  ..
12371         ZWE 2013-01-01        1      1    1    1    0   1
12372         ZWE 2014-01-01        1      1    1    1    0   1
12373         ZWE 2015-01-01        1      1    1    1    0   1
12374         ZWE 2016-01-01        1      1    1    1    0   1
12375         ZWE 2017-01-01        1      1    1    1    0   1

[12376 rows x 8 columns]

In [ ]:
# Agregamos los datos mediante empleando el promedio
df_agrupado = df_percapita.groupby(['codigo_iso']).count()
df_agrupado

year  pop  rgdpo  pib_percapita  pib_percapita_2
codigo_iso                                                  
BRA            2    2      2              2                2
CHN            2    2      2              2                2
IDN            2    2      2              2                2
IND            2    2      2              2                2
USA            2    2      2              2                2

In [ ]:
print(df.keys())
df = df.fillna(0)
df_gb = df.groupby(['countrycode','year'])['pop'].count()
df_gb

Index(['countrycode', 'country', 'year', 'rgdpo', 'pop', 'emp', 'avh', 'hc'], dtype='object')


countrycode  year      
ABW          1950-01-01    1
             1951-01-01    1
             1952-01-01    1
             1953-01-01    1
             1954-01-01    1
                          ..
ZWE          2013-01-01    1
             2014-01-01    1
             2015-01-01    1
             2016-01-01    1
             2017-01-01    1
Name: pop, Length: 12376, dtype: int64

In [ ]:
print(df.keys())
df = df.fillna(0)
df_gb = df.groupby(['countrycode','year'])['pop'].sum()
df_gb

Index(['countrycode', 'country', 'year', 'rgdpo', 'pop', 'emp', 'avh', 'hc'], dtype='object')


countrycode  year      
ABW          1950-01-01     0
             1951-01-01     0
             1952-01-01     0
             1953-01-01     0
             1954-01-01     0
                           ..
ZWE          2013-01-01    15
             2014-01-01    15
             2015-01-01    15
             2016-01-01    16
             2017-01-01    16
Name: pop, Length: 12376, dtype: int64

In [ ]:

#df_gb = df_gb.reset_index()
print(df.keys())
df[df['countrycode'] == 'BRA']

Index(['countrycode', 'country', 'year', 'rgdpo', 'pop', 'emp', 'avh', 'hc'], dtype='object')


countrycode country       year         rgdpo  pop         emp  \
1632         BRA  Brazil 1950-01-01  8.039127e+04   53   19.505514   
1633         BRA  Brazil 1951-01-01  8.280485e+04   54   20.049252   
1634         BRA  Brazil 1952-01-01  9.162370e+04   56   20.612316   
1635         BRA  Brazil 1953-01-01  9.437516e+04   58   21.195559   
1636         BRA  Brazil 1954-01-01  1.025050e+05   59   21.799868   
...          ...     ...        ...           ...  ...         ...   
1695         BRA  Brazil 2013-01-01  3.072402e+06  202  102.048592   
1696         BRA  Brazil 2014-01-01  3.069772e+06  204  105.044907   
1697         BRA  Brazil 2015-01-01  2.939667e+06  205  105.355797   
1698         BRA  Brazil 2016-01-01  2.863053e+06  207  103.496231   
1699         BRA  Brazil 2017-01-01  2.890898e+06  209  103.491943   

              avh        hc  
1632  2042.000000  1.300444  
1633  2051.018555  1.308093  
1634  2060.077148  1.315788  
1635  2069.175537  1.323528  
1636  2078.314209  1.331313  
...           ...       ...  
1695  1755.632324  2.684305  
1696  1739.474731  2.748222  
1697  1709.485596  2.813660  
1698  1709.485596  2.880657  
1699  1709.485596  2.949250  

[68 rows x 8 columns]

>**Ejercicio 3:** Generar un nuevo dataframe llamado `df_final` realizando un agrupamiento por el `codigo_pais` obteniendo los valores máximos y mínimos `['max', 'min']` del dataframe `df_percapita`

In [ ]:
#Su código aquí
df_final = df_gb.groupby(level = 0).agg(['max','min'])
df_final


max  min
countrycode          
ABW            0    0
AGO           29    0
AIA            0    0
ALB            3    0
ARE            9    0
...          ...  ...
VNM           95    0
YEM           28    0
ZAF           56   13
ZMB           17    0
ZWE           16    0

[182 rows x 2 columns]

In [ ]:
#Su código aquí
df_final = df_gb.groupby('countrycode').agg(['max','min'])
df_final

max  min
countrycode          
ABW            0    0
AGO           29    0
AIA            0    0
ALB            3    0
ARE            9    0
...          ...  ...
VNM           95    0
YEM           28    0
ZAF           56   13
ZMB           17    0
ZWE           16    0

[182 rows x 2 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df_drive = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/reviews_filmaffinity.csv'
          , sep = '||')
df_drive

### Solución

In [ ]:
df_final = df_percapita.groupby(by = 'codigo_pais').agg(['max', 'min'])
df_final

### Fin



<div style="text-align: center; line-height: 0; padding-top: 9px;">
  <img src="https://storage.googleapis.com/datasets-academy/public-img/notebooks/headers/databits-footer-notebook.png" alt="Databricks Learning" style="width: 100%;">
</div>